# Generated by Django 4.0.1 on 2023-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.CharField(default='exit', max_length=4, verbose_name='año'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
    ]
