# Generated by Django 4.0.1 on 2023-01-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehiculo_año_alter_vehiculo_patente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='año',
            new_name='anio',
        ),
    ]
